# Generated by Django 4.0.3 on 2022-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_vocab_interview_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='vocab_score',
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_score_max',
            field=models.CharField(max_length=50, null=True, verbose_name='Vocab Score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_score_min',
            field=models.CharField(max_length=50, null=True, verbose_name='Vocab Score'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='vocab_interview_time',
            field=models.TimeField(null=True, verbose_name='Interview Time'),
        ),
    ]
