# Generated by Django 4.0.3 on 2022-11-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_vocab_score_lead_vocab_score_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='vocab_score_max',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vocab_score_min',
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_score',
            field=models.CharField(max_length=50, null=True, verbose_name='Vocab Score'),
        ),
    ]
